# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2cf2fa312eb58ac22280e855638e7a8c5ae484d93fac818a1225aa15e5a4fdab3ad3f5c158f135fa52839fc8786680b8f800edc90244822b44a02a5c411968aa

test:
  secret_key_base: 3f6f2c91022da8c407b1c2204313700aa7c09204dcc951600e3376ecd138dc5defcd45ee9e6ada8ab4b5d7bb7358cb51ebb139d1c325238813f4d94321886e6e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
